package com.study.cancer.model;

import java.io.Serializable;

public class Athorization implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athorization.id
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athorization.authority_level
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    private String authorityLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athorization.method_name
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    private String methodName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table athorization
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athorization.id
     *
     * @return the value of athorization.id
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athorization.id
     *
     * @param id the value for athorization.id
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athorization.authority_level
     *
     * @return the value of athorization.authority_level
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public String getAuthorityLevel() {
        return authorityLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athorization.authority_level
     *
     * @param authorityLevel the value for athorization.authority_level
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public void setAuthorityLevel(String authorityLevel) {
        this.authorityLevel = authorityLevel == null ? null : authorityLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athorization.method_name
     *
     * @return the value of athorization.method_name
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athorization.method_name
     *
     * @param methodName the value for athorization.method_name
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public void setMethodName(String methodName) {
        this.methodName = methodName == null ? null : methodName.trim();
    }
}