package com.study.cancer.model;

import java.io.Serializable;

public class Attachment implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.id
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.attachment_name
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    private String attachmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.attachment_path
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    private String attachmentPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.type
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.medical_record_no
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    private String medicalRecordNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.apply_id
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    private String applyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.treatment_process_id
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    private String treatmentProcessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table attachment
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.id
     *
     * @return the value of attachment.id
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.id
     *
     * @param id the value for attachment.id
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.attachment_name
     *
     * @return the value of attachment.attachment_name
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public String getAttachmentName() {
        return attachmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.attachment_name
     *
     * @param attachmentName the value for attachment.attachment_name
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public void setAttachmentName(String attachmentName) {
        this.attachmentName = attachmentName == null ? null : attachmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.attachment_path
     *
     * @return the value of attachment.attachment_path
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public String getAttachmentPath() {
        return attachmentPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.attachment_path
     *
     * @param attachmentPath the value for attachment.attachment_path
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public void setAttachmentPath(String attachmentPath) {
        this.attachmentPath = attachmentPath == null ? null : attachmentPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.type
     *
     * @return the value of attachment.type
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.type
     *
     * @param type the value for attachment.type
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.medical_record_no
     *
     * @return the value of attachment.medical_record_no
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public String getMedicalRecordNo() {
        return medicalRecordNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.medical_record_no
     *
     * @param medicalRecordNo the value for attachment.medical_record_no
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public void setMedicalRecordNo(String medicalRecordNo) {
        this.medicalRecordNo = medicalRecordNo == null ? null : medicalRecordNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.apply_id
     *
     * @return the value of attachment.apply_id
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public String getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.apply_id
     *
     * @param applyId the value for attachment.apply_id
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public void setApplyId(String applyId) {
        this.applyId = applyId == null ? null : applyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.treatment_process_id
     *
     * @return the value of attachment.treatment_process_id
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public String getTreatmentProcessId() {
        return treatmentProcessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.treatment_process_id
     *
     * @param treatmentProcessId the value for attachment.treatment_process_id
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public void setTreatmentProcessId(String treatmentProcessId) {
        this.treatmentProcessId = treatmentProcessId == null ? null : treatmentProcessId.trim();
    }
}