package com.study.cancer.model;

import java.io.Serializable;

public class Bed implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bed.id
     *
     * @mbggenerated Sat Apr 28 10:45:01 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bed.patient_id
     *
     * @mbggenerated Sat Apr 28 10:45:01 CST 2018
     */
    private String patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bed.state
     *
     * @mbggenerated Sat Apr 28 10:45:01 CST 2018
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bed.bed_no
     *
     * @mbggenerated Sat Apr 28 10:45:01 CST 2018
     */
    private String bedNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bed
     *
     * @mbggenerated Sat Apr 28 10:45:01 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bed.id
     *
     * @return the value of bed.id
     *
     * @mbggenerated Sat Apr 28 10:45:01 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bed.id
     *
     * @param id the value for bed.id
     *
     * @mbggenerated Sat Apr 28 10:45:01 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bed.patient_id
     *
     * @return the value of bed.patient_id
     *
     * @mbggenerated Sat Apr 28 10:45:01 CST 2018
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bed.patient_id
     *
     * @param patientId the value for bed.patient_id
     *
     * @mbggenerated Sat Apr 28 10:45:01 CST 2018
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId == null ? null : patientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bed.state
     *
     * @return the value of bed.state
     *
     * @mbggenerated Sat Apr 28 10:45:01 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bed.state
     *
     * @param state the value for bed.state
     *
     * @mbggenerated Sat Apr 28 10:45:01 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bed.bed_no
     *
     * @return the value of bed.bed_no
     *
     * @mbggenerated Sat Apr 28 10:45:01 CST 2018
     */
    public String getBedNo() {
        return bedNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bed.bed_no
     *
     * @param bedNo the value for bed.bed_no
     *
     * @mbggenerated Sat Apr 28 10:45:01 CST 2018
     */
    public void setBedNo(String bedNo) {
        this.bedNo = bedNo == null ? null : bedNo.trim();
    }
}