package com.study.cancer.model;

import java.io.Serializable;

public class Bed implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bed.id
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bed.patient_id
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    private String patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bed.state
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bed
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bed.id
     *
     * @return the value of bed.id
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bed.id
     *
     * @param id the value for bed.id
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bed.patient_id
     *
     * @return the value of bed.patient_id
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bed.patient_id
     *
     * @param patientId the value for bed.patient_id
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId == null ? null : patientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bed.state
     *
     * @return the value of bed.state
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bed.state
     *
     * @param state the value for bed.state
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}