package com.study.cancer.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;

public class LeaveData implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_data.id
     *
     * @mbggenerated Wed May 02 20:47:11 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_data.leucocyte_concentration
     *
     * @mbggenerated Wed May 02 20:47:11 CST 2018
     */
    private String leucocyteConcentration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_data.neutrophil_concentration
     *
     * @mbggenerated Wed May 02 20:47:11 CST 2018
     */
    private String neutrophilConcentration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_data.submit_date
     *
     * @mbggenerated Wed May 02 20:47:11 CST 2018
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date submitDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_data.medical_record_no
     *
     * @mbggenerated Wed May 02 20:47:11 CST 2018
     */
    private String medicalRecordNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_data.is_checked
     *
     * @mbggenerated Wed May 02 20:47:11 CST 2018
     */
    private String isChecked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table leave_data
     *
     * @mbggenerated Wed May 02 20:47:11 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_data.id
     *
     * @return the value of leave_data.id
     *
     * @mbggenerated Wed May 02 20:47:11 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_data.id
     *
     * @param id the value for leave_data.id
     *
     * @mbggenerated Wed May 02 20:47:11 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_data.leucocyte_concentration
     *
     * @return the value of leave_data.leucocyte_concentration
     *
     * @mbggenerated Wed May 02 20:47:11 CST 2018
     */
    public String getLeucocyteConcentration() {
        return leucocyteConcentration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_data.leucocyte_concentration
     *
     * @param leucocyteConcentration the value for leave_data.leucocyte_concentration
     *
     * @mbggenerated Wed May 02 20:47:11 CST 2018
     */
    public void setLeucocyteConcentration(String leucocyteConcentration) {
        this.leucocyteConcentration = leucocyteConcentration == null ? null : leucocyteConcentration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_data.neutrophil_concentration
     *
     * @return the value of leave_data.neutrophil_concentration
     *
     * @mbggenerated Wed May 02 20:47:11 CST 2018
     */
    public String getNeutrophilConcentration() {
        return neutrophilConcentration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_data.neutrophil_concentration
     *
     * @param neutrophilConcentration the value for leave_data.neutrophil_concentration
     *
     * @mbggenerated Wed May 02 20:47:11 CST 2018
     */
    public void setNeutrophilConcentration(String neutrophilConcentration) {
        this.neutrophilConcentration = neutrophilConcentration == null ? null : neutrophilConcentration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_data.submit_date
     *
     * @return the value of leave_data.submit_date
     *
     * @mbggenerated Wed May 02 20:47:11 CST 2018
     */
    public Date getSubmitDate() {
        return submitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_data.submit_date
     *
     * @param submitDate the value for leave_data.submit_date
     *
     * @mbggenerated Wed May 02 20:47:11 CST 2018
     */
    public void setSubmitDate(Date submitDate) {
        this.submitDate = submitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_data.medical_record_no
     *
     * @return the value of leave_data.medical_record_no
     *
     * @mbggenerated Wed May 02 20:47:11 CST 2018
     */
    public String getMedicalRecordNo() {
        return medicalRecordNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_data.medical_record_no
     *
     * @param medicalRecordNo the value for leave_data.medical_record_no
     *
     * @mbggenerated Wed May 02 20:47:11 CST 2018
     */
    public void setMedicalRecordNo(String medicalRecordNo) {
        this.medicalRecordNo = medicalRecordNo == null ? null : medicalRecordNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_data.is_checked
     *
     * @return the value of leave_data.is_checked
     *
     * @mbggenerated Wed May 02 20:47:11 CST 2018
     */
    public String getIsChecked() {
        return isChecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_data.is_checked
     *
     * @param isChecked the value for leave_data.is_checked
     *
     * @mbggenerated Wed May 02 20:47:11 CST 2018
     */
    public void setIsChecked(String isChecked) {
        this.isChecked = isChecked == null ? null : isChecked.trim();
    }
}