package com.study.cancer.model;

import java.io.Serializable;
import java.util.Date;

public class LeaveRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_record.id
     *
     * @mbggenerated Mon Apr 09 09:30:57 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_record.leave_date
     *
     * @mbggenerated Mon Apr 09 09:30:57 CST 2018
     */
    private Date leaveDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_record.type
     *
     * @mbggenerated Mon Apr 09 09:30:57 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table leave_record
     *
     * @mbggenerated Mon Apr 09 09:30:57 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_record.id
     *
     * @return the value of leave_record.id
     *
     * @mbggenerated Mon Apr 09 09:30:57 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_record.id
     *
     * @param id the value for leave_record.id
     *
     * @mbggenerated Mon Apr 09 09:30:57 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_record.leave_date
     *
     * @return the value of leave_record.leave_date
     *
     * @mbggenerated Mon Apr 09 09:30:57 CST 2018
     */
    public Date getLeaveDate() {
        return leaveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_record.leave_date
     *
     * @param leaveDate the value for leave_record.leave_date
     *
     * @mbggenerated Mon Apr 09 09:30:57 CST 2018
     */
    public void setLeaveDate(Date leaveDate) {
        this.leaveDate = leaveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_record.type
     *
     * @return the value of leave_record.type
     *
     * @mbggenerated Mon Apr 09 09:30:57 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_record.type
     *
     * @param type the value for leave_record.type
     *
     * @mbggenerated Mon Apr 09 09:30:57 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}