package com.study.cancer.model;

import java.io.Serializable;
import java.util.Date;

public class leaveData implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_data.id
     *
     * @mbggenerated Fri Apr 27 17:06:16 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_data.leucocyte_concentration
     *
     * @mbggenerated Fri Apr 27 17:06:16 CST 2018
     */
    private String leucocyteConcentration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_data.neutrophil_concentration
     *
     * @mbggenerated Fri Apr 27 17:06:16 CST 2018
     */
    private String neutrophilConcentration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_data.submit_date
     *
     * @mbggenerated Fri Apr 27 17:06:16 CST 2018
     */
    private Date submitDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_data.patient_id
     *
     * @mbggenerated Fri Apr 27 17:06:16 CST 2018
     */
    private Integer patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table leave_data
     *
     * @mbggenerated Fri Apr 27 17:06:16 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_data.id
     *
     * @return the value of leave_data.id
     *
     * @mbggenerated Fri Apr 27 17:06:16 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_data.id
     *
     * @param id the value for leave_data.id
     *
     * @mbggenerated Fri Apr 27 17:06:16 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_data.leucocyte_concentration
     *
     * @return the value of leave_data.leucocyte_concentration
     *
     * @mbggenerated Fri Apr 27 17:06:16 CST 2018
     */
    public String getLeucocyteConcentration() {
        return leucocyteConcentration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_data.leucocyte_concentration
     *
     * @param leucocyteConcentration the value for leave_data.leucocyte_concentration
     *
     * @mbggenerated Fri Apr 27 17:06:16 CST 2018
     */
    public void setLeucocyteConcentration(String leucocyteConcentration) {
        this.leucocyteConcentration = leucocyteConcentration == null ? null : leucocyteConcentration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_data.neutrophil_concentration
     *
     * @return the value of leave_data.neutrophil_concentration
     *
     * @mbggenerated Fri Apr 27 17:06:16 CST 2018
     */
    public String getNeutrophilConcentration() {
        return neutrophilConcentration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_data.neutrophil_concentration
     *
     * @param neutrophilConcentration the value for leave_data.neutrophil_concentration
     *
     * @mbggenerated Fri Apr 27 17:06:16 CST 2018
     */
    public void setNeutrophilConcentration(String neutrophilConcentration) {
        this.neutrophilConcentration = neutrophilConcentration == null ? null : neutrophilConcentration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_data.submit_date
     *
     * @return the value of leave_data.submit_date
     *
     * @mbggenerated Fri Apr 27 17:06:16 CST 2018
     */
    public Date getSubmitDate() {
        return submitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_data.submit_date
     *
     * @param submitDate the value for leave_data.submit_date
     *
     * @mbggenerated Fri Apr 27 17:06:16 CST 2018
     */
    public void setSubmitDate(Date submitDate) {
        this.submitDate = submitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_data.patient_id
     *
     * @return the value of leave_data.patient_id
     *
     * @mbggenerated Fri Apr 27 17:06:16 CST 2018
     */
    public Integer getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_data.patient_id
     *
     * @param patientId the value for leave_data.patient_id
     *
     * @mbggenerated Fri Apr 27 17:06:16 CST 2018
     */
    public void setPatientId(Integer patientId) {
        this.patientId = patientId;
    }
}