package com.study.cancer.model;

import java.io.Serializable;

public class LeucocyteNeutrophilConfigWithBLOBs extends LeucocyteNeutrophilConfig implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leucocyte_neutrophil_config.leucocyte_suggestion
     *
     * @mbggenerated Wed May 02 11:01:27 CST 2018
     */
    private String leucocyteSuggestion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leucocyte_neutrophil_config.neutrophil_suggestion
     *
     * @mbggenerated Wed May 02 11:01:27 CST 2018
     */
    private String neutrophilSuggestion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table leucocyte_neutrophil_config
     *
     * @mbggenerated Wed May 02 11:01:27 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leucocyte_neutrophil_config.leucocyte_suggestion
     *
     * @return the value of leucocyte_neutrophil_config.leucocyte_suggestion
     *
     * @mbggenerated Wed May 02 11:01:27 CST 2018
     */
    public String getLeucocyteSuggestion() {
        return leucocyteSuggestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leucocyte_neutrophil_config.leucocyte_suggestion
     *
     * @param leucocyteSuggestion the value for leucocyte_neutrophil_config.leucocyte_suggestion
     *
     * @mbggenerated Wed May 02 11:01:27 CST 2018
     */
    public void setLeucocyteSuggestion(String leucocyteSuggestion) {
        this.leucocyteSuggestion = leucocyteSuggestion == null ? null : leucocyteSuggestion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leucocyte_neutrophil_config.neutrophil_suggestion
     *
     * @return the value of leucocyte_neutrophil_config.neutrophil_suggestion
     *
     * @mbggenerated Wed May 02 11:01:27 CST 2018
     */
    public String getNeutrophilSuggestion() {
        return neutrophilSuggestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leucocyte_neutrophil_config.neutrophil_suggestion
     *
     * @param neutrophilSuggestion the value for leucocyte_neutrophil_config.neutrophil_suggestion
     *
     * @mbggenerated Wed May 02 11:01:27 CST 2018
     */
    public void setNeutrophilSuggestion(String neutrophilSuggestion) {
        this.neutrophilSuggestion = neutrophilSuggestion == null ? null : neutrophilSuggestion.trim();
    }
}