package com.study.cancer.model;

import java.io.Serializable;

public class LeucocyteNeutrophilConfig implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leucocyte_neutrophil_config.id
     *
     * @mbggenerated Wed May 02 11:01:27 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leucocyte_neutrophil_config.leucocyte
     *
     * @mbggenerated Wed May 02 11:01:27 CST 2018
     */
    private String leucocyte;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leucocyte_neutrophil_config.neutrophil
     *
     * @mbggenerated Wed May 02 11:01:27 CST 2018
     */
    private String neutrophil;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leucocyte_neutrophil_config.danger_leucocyte
     *
     * @mbggenerated Wed May 02 11:01:27 CST 2018
     */
    private String dangerLeucocyte;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leucocyte_neutrophil_config.danger_neutrophil
     *
     * @mbggenerated Wed May 02 11:01:27 CST 2018
     */
    private String dangerNeutrophil;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table leucocyte_neutrophil_config
     *
     * @mbggenerated Wed May 02 11:01:27 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leucocyte_neutrophil_config.id
     *
     * @return the value of leucocyte_neutrophil_config.id
     *
     * @mbggenerated Wed May 02 11:01:27 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leucocyte_neutrophil_config.id
     *
     * @param id the value for leucocyte_neutrophil_config.id
     *
     * @mbggenerated Wed May 02 11:01:27 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leucocyte_neutrophil_config.leucocyte
     *
     * @return the value of leucocyte_neutrophil_config.leucocyte
     *
     * @mbggenerated Wed May 02 11:01:27 CST 2018
     */
    public String getLeucocyte() {
        return leucocyte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leucocyte_neutrophil_config.leucocyte
     *
     * @param leucocyte the value for leucocyte_neutrophil_config.leucocyte
     *
     * @mbggenerated Wed May 02 11:01:27 CST 2018
     */
    public void setLeucocyte(String leucocyte) {
        this.leucocyte = leucocyte == null ? null : leucocyte.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leucocyte_neutrophil_config.neutrophil
     *
     * @return the value of leucocyte_neutrophil_config.neutrophil
     *
     * @mbggenerated Wed May 02 11:01:27 CST 2018
     */
    public String getNeutrophil() {
        return neutrophil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leucocyte_neutrophil_config.neutrophil
     *
     * @param neutrophil the value for leucocyte_neutrophil_config.neutrophil
     *
     * @mbggenerated Wed May 02 11:01:27 CST 2018
     */
    public void setNeutrophil(String neutrophil) {
        this.neutrophil = neutrophil == null ? null : neutrophil.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leucocyte_neutrophil_config.danger_leucocyte
     *
     * @return the value of leucocyte_neutrophil_config.danger_leucocyte
     *
     * @mbggenerated Wed May 02 11:01:27 CST 2018
     */
    public String getDangerLeucocyte() {
        return dangerLeucocyte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leucocyte_neutrophil_config.danger_leucocyte
     *
     * @param dangerLeucocyte the value for leucocyte_neutrophil_config.danger_leucocyte
     *
     * @mbggenerated Wed May 02 11:01:27 CST 2018
     */
    public void setDangerLeucocyte(String dangerLeucocyte) {
        this.dangerLeucocyte = dangerLeucocyte == null ? null : dangerLeucocyte.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leucocyte_neutrophil_config.danger_neutrophil
     *
     * @return the value of leucocyte_neutrophil_config.danger_neutrophil
     *
     * @mbggenerated Wed May 02 11:01:27 CST 2018
     */
    public String getDangerNeutrophil() {
        return dangerNeutrophil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leucocyte_neutrophil_config.danger_neutrophil
     *
     * @param dangerNeutrophil the value for leucocyte_neutrophil_config.danger_neutrophil
     *
     * @mbggenerated Wed May 02 11:01:27 CST 2018
     */
    public void setDangerNeutrophil(String dangerNeutrophil) {
        this.dangerNeutrophil = dangerNeutrophil == null ? null : dangerNeutrophil.trim();
    }
}