package com.study.cancer.model;

import java.io.Serializable;
import java.util.Date;

public class MedicalRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_record.id
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_record.patient_id
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    private Integer patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_record.first_in_hospital_date
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    private Date firstInHospitalDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_record.severity
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    private String severity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_record.is_in_hospital
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    private String isInHospital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_record.chemotherapy_interval
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    private String chemotherapyInterval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_record.chemotherapy_cycle
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    private String chemotherapyCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table medical_record
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.id
     *
     * @return the value of medical_record.id
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.id
     *
     * @param id the value for medical_record.id
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.patient_id
     *
     * @return the value of medical_record.patient_id
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public Integer getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.patient_id
     *
     * @param patientId the value for medical_record.patient_id
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public void setPatientId(Integer patientId) {
        this.patientId = patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.first_in_hospital_date
     *
     * @return the value of medical_record.first_in_hospital_date
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public Date getFirstInHospitalDate() {
        return firstInHospitalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.first_in_hospital_date
     *
     * @param firstInHospitalDate the value for medical_record.first_in_hospital_date
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public void setFirstInHospitalDate(Date firstInHospitalDate) {
        this.firstInHospitalDate = firstInHospitalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.severity
     *
     * @return the value of medical_record.severity
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public String getSeverity() {
        return severity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.severity
     *
     * @param severity the value for medical_record.severity
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public void setSeverity(String severity) {
        this.severity = severity == null ? null : severity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.is_in_hospital
     *
     * @return the value of medical_record.is_in_hospital
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public String getIsInHospital() {
        return isInHospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.is_in_hospital
     *
     * @param isInHospital the value for medical_record.is_in_hospital
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public void setIsInHospital(String isInHospital) {
        this.isInHospital = isInHospital == null ? null : isInHospital.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.chemotherapy_interval
     *
     * @return the value of medical_record.chemotherapy_interval
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public String getChemotherapyInterval() {
        return chemotherapyInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.chemotherapy_interval
     *
     * @param chemotherapyInterval the value for medical_record.chemotherapy_interval
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public void setChemotherapyInterval(String chemotherapyInterval) {
        this.chemotherapyInterval = chemotherapyInterval == null ? null : chemotherapyInterval.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.chemotherapy_cycle
     *
     * @return the value of medical_record.chemotherapy_cycle
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public String getChemotherapyCycle() {
        return chemotherapyCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.chemotherapy_cycle
     *
     * @param chemotherapyCycle the value for medical_record.chemotherapy_cycle
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public void setChemotherapyCycle(String chemotherapyCycle) {
        this.chemotherapyCycle = chemotherapyCycle == null ? null : chemotherapyCycle.trim();
    }
}