package com.study.cancer.model;

import java.io.Serializable;

public class MedicalGroup implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_group.id
     *
     * @mbggenerated Mon Apr 30 17:03:37 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_group.name
     *
     * @mbggenerated Mon Apr 30 17:03:37 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table medical_group
     *
     * @mbggenerated Mon Apr 30 17:03:37 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_group.id
     *
     * @return the value of medical_group.id
     *
     * @mbggenerated Mon Apr 30 17:03:37 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_group.id
     *
     * @param id the value for medical_group.id
     *
     * @mbggenerated Mon Apr 30 17:03:37 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_group.name
     *
     * @return the value of medical_group.name
     *
     * @mbggenerated Mon Apr 30 17:03:37 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_group.name
     *
     * @param name the value for medical_group.name
     *
     * @mbggenerated Mon Apr 30 17:03:37 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}