package com.study.cancer.model;

import java.io.Serializable;

public class Menue implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menue.id
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menue.authority_level
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    private String authorityLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menue.level
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menue.node_text
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    private String nodeText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menue.url
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menue.parent_node
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    private String parentNode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menue.hasChild
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    private String haschild;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menue
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menue.id
     *
     * @return the value of menue.id
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menue.id
     *
     * @param id the value for menue.id
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menue.authority_level
     *
     * @return the value of menue.authority_level
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public String getAuthorityLevel() {
        return authorityLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menue.authority_level
     *
     * @param authorityLevel the value for menue.authority_level
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public void setAuthorityLevel(String authorityLevel) {
        this.authorityLevel = authorityLevel == null ? null : authorityLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menue.level
     *
     * @return the value of menue.level
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menue.level
     *
     * @param level the value for menue.level
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menue.node_text
     *
     * @return the value of menue.node_text
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public String getNodeText() {
        return nodeText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menue.node_text
     *
     * @param nodeText the value for menue.node_text
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public void setNodeText(String nodeText) {
        this.nodeText = nodeText == null ? null : nodeText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menue.url
     *
     * @return the value of menue.url
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menue.url
     *
     * @param url the value for menue.url
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menue.parent_node
     *
     * @return the value of menue.parent_node
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public String getParentNode() {
        return parentNode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menue.parent_node
     *
     * @param parentNode the value for menue.parent_node
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public void setParentNode(String parentNode) {
        this.parentNode = parentNode == null ? null : parentNode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menue.hasChild
     *
     * @return the value of menue.hasChild
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public String getHaschild() {
        return haschild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menue.hasChild
     *
     * @param haschild the value for menue.hasChild
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    public void setHaschild(String haschild) {
        this.haschild = haschild == null ? null : haschild.trim();
    }
}