package com.study.cancer.model;

import java.io.Serializable;

public class Message implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbggenerated Thu Mar 29 09:09:20 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.tab_title
     *
     * @mbggenerated Thu Mar 29 09:09:20 CST 2018
     */
    private String tabTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.url
     *
     * @mbggenerated Thu Mar 29 09:09:20 CST 2018
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.state
     *
     * @mbggenerated Thu Mar 29 09:09:20 CST 2018
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.send_to
     *
     * @mbggenerated Thu Mar 29 09:09:20 CST 2018
     */
    private Integer sendTo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.send_from
     *
     * @mbggenerated Thu Mar 29 09:09:20 CST 2018
     */
    private Integer sendFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.type
     *
     * @mbggenerated Thu Mar 29 09:09:20 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.content
     *
     * @mbggenerated Thu Mar 29 09:09:20 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message
     *
     * @mbggenerated Thu Mar 29 09:09:20 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbggenerated Thu Mar 29 09:09:20 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbggenerated Thu Mar 29 09:09:20 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.tab_title
     *
     * @return the value of message.tab_title
     *
     * @mbggenerated Thu Mar 29 09:09:20 CST 2018
     */
    public String getTabTitle() {
        return tabTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.tab_title
     *
     * @param tabTitle the value for message.tab_title
     *
     * @mbggenerated Thu Mar 29 09:09:20 CST 2018
     */
    public void setTabTitle(String tabTitle) {
        this.tabTitle = tabTitle == null ? null : tabTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.url
     *
     * @return the value of message.url
     *
     * @mbggenerated Thu Mar 29 09:09:20 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.url
     *
     * @param url the value for message.url
     *
     * @mbggenerated Thu Mar 29 09:09:20 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.state
     *
     * @return the value of message.state
     *
     * @mbggenerated Thu Mar 29 09:09:20 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.state
     *
     * @param state the value for message.state
     *
     * @mbggenerated Thu Mar 29 09:09:20 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.send_to
     *
     * @return the value of message.send_to
     *
     * @mbggenerated Thu Mar 29 09:09:20 CST 2018
     */
    public Integer getSendTo() {
        return sendTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.send_to
     *
     * @param sendTo the value for message.send_to
     *
     * @mbggenerated Thu Mar 29 09:09:20 CST 2018
     */
    public void setSendTo(Integer sendTo) {
        this.sendTo = sendTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.send_from
     *
     * @return the value of message.send_from
     *
     * @mbggenerated Thu Mar 29 09:09:20 CST 2018
     */
    public Integer getSendFrom() {
        return sendFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.send_from
     *
     * @param sendFrom the value for message.send_from
     *
     * @mbggenerated Thu Mar 29 09:09:20 CST 2018
     */
    public void setSendFrom(Integer sendFrom) {
        this.sendFrom = sendFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.type
     *
     * @return the value of message.type
     *
     * @mbggenerated Thu Mar 29 09:09:20 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.type
     *
     * @param type the value for message.type
     *
     * @mbggenerated Thu Mar 29 09:09:20 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.content
     *
     * @return the value of message.content
     *
     * @mbggenerated Thu Mar 29 09:09:20 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.content
     *
     * @param content the value for message.content
     *
     * @mbggenerated Thu Mar 29 09:09:20 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}