package com.study.cancer.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;

public class Message implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbggenerated Tue Apr 03 17:28:45 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.tab_title
     *
     * @mbggenerated Tue Apr 03 17:28:45 CST 2018
     */
    private String tabTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.url
     *
     * @mbggenerated Tue Apr 03 17:28:45 CST 2018
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.state
     *
     * @mbggenerated Tue Apr 03 17:28:45 CST 2018
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.send_to
     *
     * @mbggenerated Tue Apr 03 17:28:45 CST 2018
     */
    private Integer sendTo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.send_from
     *
     * @mbggenerated Tue Apr 03 17:28:45 CST 2018
     */
    private Integer sendFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message_type
     *
     * @mbggenerated Tue Apr 03 17:28:45 CST 2018
     */
    private String messageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.send_date
     *
     * @mbggenerated Tue Apr 03 17:28:45 CST 2018
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date sendDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.send_from_name
     *
     * @mbggenerated Tue Apr 03 17:28:45 CST 2018
     */
    private String sendFromName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.content
     *
     * @mbggenerated Tue Apr 03 17:28:45 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message
     *
     * @mbggenerated Tue Apr 03 17:28:45 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbggenerated Tue Apr 03 17:28:45 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbggenerated Tue Apr 03 17:28:45 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.tab_title
     *
     * @return the value of message.tab_title
     *
     * @mbggenerated Tue Apr 03 17:28:45 CST 2018
     */
    public String getTabTitle() {
        return tabTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.tab_title
     *
     * @param tabTitle the value for message.tab_title
     *
     * @mbggenerated Tue Apr 03 17:28:45 CST 2018
     */
    public void setTabTitle(String tabTitle) {
        this.tabTitle = tabTitle == null ? null : tabTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.url
     *
     * @return the value of message.url
     *
     * @mbggenerated Tue Apr 03 17:28:45 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.url
     *
     * @param url the value for message.url
     *
     * @mbggenerated Tue Apr 03 17:28:45 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.state
     *
     * @return the value of message.state
     *
     * @mbggenerated Tue Apr 03 17:28:45 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.state
     *
     * @param state the value for message.state
     *
     * @mbggenerated Tue Apr 03 17:28:45 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.send_to
     *
     * @return the value of message.send_to
     *
     * @mbggenerated Tue Apr 03 17:28:45 CST 2018
     */
    public Integer getSendTo() {
        return sendTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.send_to
     *
     * @param sendTo the value for message.send_to
     *
     * @mbggenerated Tue Apr 03 17:28:45 CST 2018
     */
    public void setSendTo(Integer sendTo) {
        this.sendTo = sendTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.send_from
     *
     * @return the value of message.send_from
     *
     * @mbggenerated Tue Apr 03 17:28:45 CST 2018
     */
    public Integer getSendFrom() {
        return sendFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.send_from
     *
     * @param sendFrom the value for message.send_from
     *
     * @mbggenerated Tue Apr 03 17:28:45 CST 2018
     */
    public void setSendFrom(Integer sendFrom) {
        this.sendFrom = sendFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message_type
     *
     * @return the value of message.message_type
     *
     * @mbggenerated Tue Apr 03 17:28:45 CST 2018
     */
    public String getMessageType() {
        return messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.message_type
     *
     * @param messageType the value for message.message_type
     *
     * @mbggenerated Tue Apr 03 17:28:45 CST 2018
     */
    public void setMessageType(String messageType) {
        this.messageType = messageType == null ? null : messageType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.send_date
     *
     * @return the value of message.send_date
     *
     * @mbggenerated Tue Apr 03 17:28:45 CST 2018
     */
    public Date getSendDate() {
        return sendDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.send_date
     *
     * @param sendDate the value for message.send_date
     *
     * @mbggenerated Tue Apr 03 17:28:45 CST 2018
     */
    public void setSendDate(Date sendDate) {
        this.sendDate = sendDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.send_from_name
     *
     * @return the value of message.send_from_name
     *
     * @mbggenerated Tue Apr 03 17:28:45 CST 2018
     */
    public String getSendFromName() {
        return sendFromName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.send_from_name
     *
     * @param sendFromName the value for message.send_from_name
     *
     * @mbggenerated Tue Apr 03 17:28:45 CST 2018
     */
    public void setSendFromName(String sendFromName) {
        this.sendFromName = sendFromName == null ? null : sendFromName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.content
     *
     * @return the value of message.content
     *
     * @mbggenerated Tue Apr 03 17:28:45 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.content
     *
     * @param content the value for message.content
     *
     * @mbggenerated Tue Apr 03 17:28:45 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}