package com.study.cancer.model;

import java.io.Serializable;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sex
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id_card_no
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    private String idCardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone_number
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.athorization
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    private String athorization;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.medical_group
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    private String medicalGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.age
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_group_leader
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    private String isGroupLeader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.break_times
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    private Integer breakTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sex
     *
     * @return the value of user.sex
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sex
     *
     * @param sex the value for user.sex
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id_card_no
     *
     * @return the value of user.id_card_no
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    public String getIdCardNo() {
        return idCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id_card_no
     *
     * @param idCardNo the value for user.id_card_no
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    public void setIdCardNo(String idCardNo) {
        this.idCardNo = idCardNo == null ? null : idCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone_number
     *
     * @return the value of user.phone_number
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone_number
     *
     * @param phoneNumber the value for user.phone_number
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.athorization
     *
     * @return the value of user.athorization
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    public String getAthorization() {
        return athorization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.athorization
     *
     * @param athorization the value for user.athorization
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    public void setAthorization(String athorization) {
        this.athorization = athorization == null ? null : athorization.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.medical_group
     *
     * @return the value of user.medical_group
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    public String getMedicalGroup() {
        return medicalGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.medical_group
     *
     * @param medicalGroup the value for user.medical_group
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    public void setMedicalGroup(String medicalGroup) {
        this.medicalGroup = medicalGroup == null ? null : medicalGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.age
     *
     * @return the value of user.age
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.age
     *
     * @param age the value for user.age
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_group_leader
     *
     * @return the value of user.is_group_leader
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    public String getIsGroupLeader() {
        return isGroupLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_group_leader
     *
     * @param isGroupLeader the value for user.is_group_leader
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    public void setIsGroupLeader(String isGroupLeader) {
        this.isGroupLeader = isGroupLeader == null ? null : isGroupLeader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.break_times
     *
     * @return the value of user.break_times
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    public Integer getBreakTimes() {
        return breakTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.break_times
     *
     * @param breakTimes the value for user.break_times
     *
     * @mbggenerated Thu May 03 10:30:27 CST 2018
     */
    public void setBreakTimes(Integer breakTimes) {
        this.breakTimes = breakTimes;
    }
}