package com.study.cancer.dao;

import com.study.cancer.model.Athorization;

public interface AthorizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athorization
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athorization
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    int insert(Athorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athorization
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    int insertSelective(Athorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athorization
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    Athorization selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athorization
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    int updateByPrimaryKeySelective(Athorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athorization
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    int updateByPrimaryKey(Athorization record);
}