package com.study.cancer.dao;

import com.study.cancer.model.Bed;

import java.util.List;

public interface BedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bed
     *
     * @mbggenerated Sat Apr 28 10:45:01 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bed
     *
     * @mbggenerated Sat Apr 28 10:45:01 CST 2018
     */
    int insert(Bed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bed
     *
     * @mbggenerated Sat Apr 28 10:45:01 CST 2018
     */
    int insertSelective(Bed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bed
     *
     * @mbggenerated Sat Apr 28 10:45:01 CST 2018
     */
    Bed selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bed
     *
     * @mbggenerated Sat Apr 28 10:45:01 CST 2018
     */
    int updateByPrimaryKeySelective(Bed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bed
     *
     * @mbggenerated Sat Apr 28 10:45:01 CST 2018
     */
    int updateByPrimaryKey(Bed record);

    List<Bed> selectNumByState(String state);
}