package com.study.cancer.dao;

import com.study.cancer.model.LeaveData;

public interface LeaveDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_data
     *
     * @mbggenerated Mon Apr 30 17:03:37 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_data
     *
     * @mbggenerated Mon Apr 30 17:03:37 CST 2018
     */
    int insert(LeaveData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_data
     *
     * @mbggenerated Mon Apr 30 17:03:37 CST 2018
     */
    int insertSelective(LeaveData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_data
     *
     * @mbggenerated Mon Apr 30 17:03:37 CST 2018
     */
    LeaveData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_data
     *
     * @mbggenerated Mon Apr 30 17:03:37 CST 2018
     */
    int updateByPrimaryKeySelective(LeaveData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_data
     *
     * @mbggenerated Mon Apr 30 17:03:37 CST 2018
     */
    int updateByPrimaryKey(LeaveData record);
}