package com.study.cancer.dao;

import com.study.cancer.model.LeaveData;

import java.util.List;

public interface LeaveDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_data
     *
     * @mbggenerated Wed May 02 20:47:11 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_data
     *
     * @mbggenerated Wed May 02 20:47:11 CST 2018
     */
    int insert(LeaveData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_data
     *
     * @mbggenerated Wed May 02 20:47:11 CST 2018
     */
    int insertSelective(LeaveData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_data
     *
     * @mbggenerated Wed May 02 20:47:11 CST 2018
     */
    LeaveData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_data
     *
     * @mbggenerated Wed May 02 20:47:11 CST 2018
     */
    int updateByPrimaryKeySelective(LeaveData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_data
     *
     * @mbggenerated Wed May 02 20:47:11 CST 2018
     */
    int updateByPrimaryKey(LeaveData record);

    List<LeaveData> selectWeekData(String medicalRecordNo);
}