package com.study.cancer.dao;

import com.study.cancer.model.LeaveRecord;

public interface LeaveRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_record
     *
     * @mbggenerated Sun Apr 29 23:46:24 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_record
     *
     * @mbggenerated Sun Apr 29 23:46:24 CST 2018
     */
    int insert(LeaveRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_record
     *
     * @mbggenerated Sun Apr 29 23:46:24 CST 2018
     */
    int insertSelective(LeaveRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_record
     *
     * @mbggenerated Sun Apr 29 23:46:24 CST 2018
     */
    LeaveRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_record
     *
     * @mbggenerated Sun Apr 29 23:46:24 CST 2018
     */
    int updateByPrimaryKeySelective(LeaveRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_record
     *
     * @mbggenerated Sun Apr 29 23:46:24 CST 2018
     */
    int updateByPrimaryKey(LeaveRecord record);
}