package com.study.cancer.dao;

import com.study.cancer.model.LeucocyteNeutrophilConfig;
import com.study.cancer.model.LeucocyteNeutrophilConfigWithBLOBs;

public interface LeucocyteNeutrophilConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leucocyte_neutrophil_config
     *
     * @mbggenerated Wed May 02 11:01:27 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leucocyte_neutrophil_config
     *
     * @mbggenerated Wed May 02 11:01:27 CST 2018
     */
    int insert(LeucocyteNeutrophilConfigWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leucocyte_neutrophil_config
     *
     * @mbggenerated Wed May 02 11:01:27 CST 2018
     */
    int insertSelective(LeucocyteNeutrophilConfigWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leucocyte_neutrophil_config
     *
     * @mbggenerated Wed May 02 11:01:27 CST 2018
     */
    LeucocyteNeutrophilConfigWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leucocyte_neutrophil_config
     *
     * @mbggenerated Wed May 02 11:01:27 CST 2018
     */
    int updateByPrimaryKeySelective(LeucocyteNeutrophilConfigWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leucocyte_neutrophil_config
     *
     * @mbggenerated Wed May 02 11:01:27 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(LeucocyteNeutrophilConfigWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leucocyte_neutrophil_config
     *
     * @mbggenerated Wed May 02 11:01:27 CST 2018
     */
    int updateByPrimaryKey(LeucocyteNeutrophilConfig record);
}