package com.study.cancer.dao;

import com.study.cancer.model.MedicalGroup;

import java.util.List;

public interface MedicalGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_group
     *
     * @mbggenerated Mon Apr 30 17:03:37 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_group
     *
     * @mbggenerated Mon Apr 30 17:03:37 CST 2018
     */
    int insert(MedicalGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_group
     *
     * @mbggenerated Mon Apr 30 17:03:37 CST 2018
     */
    int insertSelective(MedicalGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_group
     *
     * @mbggenerated Mon Apr 30 17:03:37 CST 2018
     */
    MedicalGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_group
     *
     * @mbggenerated Mon Apr 30 17:03:37 CST 2018
     */
    int updateByPrimaryKeySelective(MedicalGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_group
     *
     * @mbggenerated Mon Apr 30 17:03:37 CST 2018
     */
    int updateByPrimaryKey(MedicalGroup record);

    List<MedicalGroup> selectList();
}