package com.study.cancer.dao;

import com.study.cancer.model.MedicalRecord;

public interface MedicalRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbggenerated Fri Apr 27 14:46:40 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbggenerated Fri Apr 27 14:46:40 CST 2018
     */
    int insert(MedicalRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbggenerated Fri Apr 27 14:46:40 CST 2018
     */
    int insertSelective(MedicalRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbggenerated Fri Apr 27 14:46:40 CST 2018
     */
    MedicalRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbggenerated Fri Apr 27 14:46:40 CST 2018
     */
    int updateByPrimaryKeySelective(MedicalRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbggenerated Fri Apr 27 14:46:40 CST 2018
     */
    int updateByPrimaryKey(MedicalRecord record);
}