package com.study.cancer.dao;

import com.study.cancer.model.Menue;

import java.util.List;

public interface MenueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menue
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menue
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    int insert(Menue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menue
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    int insertSelective(Menue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menue
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    Menue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menue
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    int updateByPrimaryKeySelective(Menue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menue
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    int updateByPrimaryKey(Menue record);

    List<Menue> selectByAuthorityLevel(String authoritylevel);
}