package com.study.cancer.dao;

import com.study.cancer.model.TreatmentProcess;

public interface TreatmentProcessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_process
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_process
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    int insert(TreatmentProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_process
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    int insertSelective(TreatmentProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_process
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    TreatmentProcess selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_process
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    int updateByPrimaryKeySelective(TreatmentProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treatment_process
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    int updateByPrimaryKey(TreatmentProcess record);
}