package com.study.cancer.dao;

import com.study.cancer.model.WaitLevelConfig;

public interface WaitLevelConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_level_config
     *
     * @mbggenerated Fri Apr 27 17:04:18 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_level_config
     *
     * @mbggenerated Fri Apr 27 17:04:18 CST 2018
     */
    int insert(WaitLevelConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_level_config
     *
     * @mbggenerated Fri Apr 27 17:04:18 CST 2018
     */
    int insertSelective(WaitLevelConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_level_config
     *
     * @mbggenerated Fri Apr 27 17:04:18 CST 2018
     */
    WaitLevelConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_level_config
     *
     * @mbggenerated Fri Apr 27 17:04:18 CST 2018
     */
    int updateByPrimaryKeySelective(WaitLevelConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_level_config
     *
     * @mbggenerated Fri Apr 27 17:04:18 CST 2018
     */
    int updateByPrimaryKey(WaitLevelConfig record);
}