package com.study.cancer.dao;

import com.study.cancer.model.WaitLevelConfig;

public interface WaitLevelConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_level_config
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    int insert(WaitLevelConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_level_config
     *
     * @mbggenerated Mon Feb 26 14:28:11 CST 2018
     */
    int insertSelective(WaitLevelConfig record);
}